### ISSUE TITLE
Bug displaying SNP names

### ISSUE THREAD

**Issue by piotyama** [cannin/snp_plotter#2]
Hi Luna,

Great tool! I am trying to display my GWAS result together with LD heatmap. I have SNP Associations w/o haplotype association. In my SNP Assoc file and genotype file, the SNPs are ordered exactly the same but in the resulting figure the SNP names do not correspond with the pvals displayed.

Everything works great except for SNP names being displayed against the wrong Pval. Could this be a bug? I would really appreciate you looking into this--hopefully it is a quick fix. Below I have attached the assoc file and the resulting figure. Notice that the SNP names do not match the P.value displayed vs what is in the asssoc file.
[arach_A04_ss.txt](https://github.com/cannin/snp_plotter/files/5833997/arach_A04_ss.txt)
[arachidic_A04.pdf](https://github.com/cannin/snp_plotter/files/5833999/arachidic_A04.pdf)

 I appreciate your help debugging this.

**Comment by cannin** [comment]
@piotyama Two possible solutions: 

# Code-Based Solution 

Try the following configuration parameters to adjust the lines. 

* CONNECTING.LINES.FACTOR: Adjusts the length of the connecting lines. Range: 0-2
* CONNECTING.LINES.ADJ: Can be used to adjust the position of connecting lines in relation to SNP names. Negative values shift the connecting lines to the left and positive values shift the lines to the right. Range: 0-1
* CONNECTING.LINES.VERT.ADJ: Can be used to vertically adjust the position of connecting lines in relation to SNP names. More negative value shift the connecting lines down. Range: -0.5-0
* CONNECTING.LINES.FLEX: Adjusts the spread of the connecting lines. Range: 0-2

# Manual Solution

I opened your PDF file in Adobe Illustrator; it was pretty simple to move the heatmap down; this is probably also possible in the free Inkscape (https://inkscape.org/).

**Comment by piotyama** [comment]
Thanks for the suggestions, the manual solution did it for me.
